apiVersion: apps/v1
kind: Deployment
metadata:
  name: library
spec:
  replicas: 1
  selector:
    matchLabels:
      app: library
  template:
    metadata:
      labels:
        app: library
    spec:
      containers:
      - name: library-container
        image: arvik786/library
        stdin: true
        tty: true